name: bore
services:
  bore:
    image: ekzhang/bore
    restart: always
    container_name: bore
    init: true
    network_mode: "host"
    command: local 35565 --to bore.pub --port 13477
    stdin_open: true
    tty: true
