name: minecraft-server
services:
  minecraft:
    restart: always
    container_name: minecraft-server
    build:
      context: ./mcserver
    ports:
      - "35565:35565"
    stdin_open: true
    tty: true
    volumes:
      - ./mcserver:/data
    networks:
      - minecraft

volumes:
  minecraft_data:
networks:
  minecraft:
