services:
    db:
        image: postgres:14.1-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        ports:
            - '5432:5432'
        volumes:
            - /var/lib/postgresql/data
            - ./db/scripts:/docker-entrypoint-initdb.d